name: Draft-Release erstellen

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Release Titel'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      commit:
        description: 'Commit SHA des Runs mit den hochzuladenen Artefakten'
        default: ''
        type: string

jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: gradle-build.yml
          workflow_conclusion: success
          name: executables
          commit: ${{ inputs.commit || github.event.pull_request.head.sha }}
      - name: Release erstellen
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 'latest'
          prerelease: false
          draft: true
          title: ${{ inputs.title || null }}
          files: |
            full/*.*
            basic/*.*
            
