name: Gradle Package

on: [push, workflow_dispatch]

jobs:   
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 16
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
      
    - name: Build Application with launch4j
      run: gradle :app:createExe
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: app/build/launch4j/

    - name: Build Commandline-Merger with launch4j
      run: gradle :merger:createExe
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: merger/build/launch4j/
