name: Gradle Package

on: [push, workflow_dispatch]

jobs:   
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 16
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle wrapper
      run: ./gradlew shadowJar
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: build/libs/
