name: Gradle Package

on:
  push:
    branches-ignore:
    - data
    paths-ignore:
    - '**.md'
    - '.idea/**'
    - '**.py'
    
  workflow_dispatch:

jobs:   
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '18'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4

    - name: Build Application with JPackage
      run: gradle :app:jpackage

    - name: Build Commandline-Merger with JPackage
      run: gradle :merger:jpackage

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: out/executable/

    - name: Build RPMs with JPackage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        gradle :app:buildRPM
        gradle :merger:buildRPM

    - name: Upload RPM build reports
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: out/executable/
