name: Gradle Package

on:
  push:
    branches-ignore:
    - data
    paths-ignore:
    - '**.md'
    - '.idea/**'
    - '**.py'
    - 'schema.json'
  workflow_dispatch:

jobs:   
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        # arch: [ x64 ]
        # java-distro: [ corretto ]
        # include: 
        #   - os: windows-latest
        #     arch: x86
        #     java-distro: zulu
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        # distribution: ${{ matrix.java-distro }}
        distribution: 'corretto'
        java-version: '18'
        # architecture: ${{ matrix.arch }}
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5

    - name: Build Application with JPackage
      run: gradle :app:jpackage

    - name: Build Commandline-Merger with JPackage
      run: gradle :merger:jpackage

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: application-${{ matrix.os }}
        path: out/executable/

    - name: Build RPMs with JPackage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        gradle :app:buildRPM
        gradle :merger:buildRPM

    - name: Upload rpm binaries
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: application-rpm
        path: out/executable/
        
  merge:
    runs-on: ubuntu-latest
    needs: gradle
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: executables
          delete-merged: true

    # - name: Rename win32 Binaries
    #   if: ${{ matrix.arch == 'x86' }}
    #   working-directory: ./out/executable/basic
    #   shell: cmd
    #   run: |
    #     for %%F in (*.msi) do RENAME %%F "%%~nF_win32.msi"
    #     cd ../full
    #     for %%F in (*.msi) do RENAME %%F "%%~nF_win32.msi"
