name: Gradle Package

on:
  push:
    branches-ignore:
    - data
    paths-ignore:
    - '**.md'
    - '.idea/**'
    - '**.py'
    - 'schema.json'
  workflow_dispatch:

jobs:   
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-13, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Build Application with JPackage
      run: ./gradlew :app:jpackage :merger:jpackage

    - name: Rename macOS x86 Binaries
      if: ${{ matrix.os == 'macos-latest' }}
      working-directory: ./out/executable
      shell: bash
      run: find . -name '*.pkg' -exec bash -c 'mv $0 ${0/.pkg/_arm64.pkg}' {} \;

    - name: Rename Apple Silicon Binaries
      if: ${{ matrix.os == 'macos-13' }}
      working-directory: ./out/executable
      shell: bash
      run: find . -name '*.pkg' -exec bash -c 'mv $0 ${0/.pkg/_intel.pkg}' {} \;

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: application-${{ matrix.os }}-${{ matrix.arch }}
        path: out/executable/


    - uses: actions/setup-java@v3
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        distribution: 'zulu'
        architecture: 'x86'
        java-version: '17'

    - name: Build 32-bit Application with JPackage
      if: ${{ matrix.os == 'windows-latest' }}
      env:
        ORG_GRADLE_PROJECT_arch: 'x86'  # arch beeinflusst nur Windows-Builds
      run: ./gradlew :app:jpackage :merger:jpackage -Dorg.gradle.java.home=${{ env.JAVA_HOME_17_X64 }}

    - name: Rename 32-bit Binaries
      if: ${{ matrix.os == 'windows-latest' }}
      working-directory: ./out/executable
      shell: bash
      run: find . -name '*.msi' -exec bash -c 'mv $0 ${0/.msi/_win32.msi}' {} \;

    - name: Upload 32-bit binaries
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: application-windows-x86
        path: out/executable/
        
  merge:
    runs-on: ubuntu-latest
    needs: gradle
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: executables
          delete-merged: true
