name: Win32 Package

on:
  push:
    branches-ignore:
    - data
    paths-ignore:
    - '**.md'
    - '.idea/**'
    - '**.py'
    
  workflow_dispatch:

jobs:   
  gradle:
    runs-on: windows-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'
        architecture: x86
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4

    - name: Build Application with JPackage
      run: gradle :app:jpackage

    - name: Build Commandline-Merger with JPackage
      run: gradle :merger:jpackage

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: out/executable/
